language: java

sudo: required

script:
  - "mkdir ./folder"
  - "chmod u+rw ./folder"
  - "mvn test integration-test -Djava.io.tmpdir=./folder -Pintegration-tests"


after_script: bash <(curl -s https://codecov.io/bash)